import jwt from "jsonwebtoken";

// Generate token
export const generateToken = (payload) => {
  const secretKey = process.env.JWT_SECRET;

  const token = jwt.sign(payload, secretKey, { expiresIn: "1d" });

  return token;
};

export const books = [
    {
        title: "The Great Gatsby",
        author: "F. Scott Fitzgerald",
        price: 12.99,
        category: "Classic",
        description: "A story of wealth, love, and the American Dream in the 1920s through the eyes of the mysterious Jay Gatsby and narrator Nick Carraway.",
        coverImage: "https://m.media-amazon.com/images/I/71FTb9X6wsL._AC_UF1000,1000_QL80_.jpg",
        rating: 4.5,
        stock: 10,
        pages: 180,
        publishedYear: 1925,
        isbn: "9780743273565",
        language: "English",
        publisher: "Scribner",
        isBookmarked: false,
    },
    {
        title: "To Kill a Mockingbird",
        author: "Harper Lee",
        price: 10.99,
        category: "Classic",
        description: "Set in the Depression-era South, this novel follows young Scout Finch as her father, Atticus, defends a Black man wrongly accused of assault.",
        coverImage: "https://m.media-amazon.com/images/I/71FxgtFKcQL._AC_UF1000,1000_QL80_.jpg",
        rating: 4.8,
        stock: 15,
        pages: 281,
        publishedYear: 1960,
        isbn: "9780061120084",
        language: "English",
        publisher: "J. B. Lippincott & Co.",
        isBookmarked: true,
    },
    {
        title: "1984",
        author: "George Orwell",
        price: 9.99,
        category: "Dystopian",
        description: "Winston Smith navigates life under the totalitarian regime of Big Brother in a world of perpetual war, omnipresent government surveillance, and public manipulation.",
        coverImage: "https://m.media-amazon.com/images/I/61ZewDE3beL._AC_UF1000,1000_QL80_.jpg",
        rating: 4.7,
        stock: 8,
        pages: 328,
        publishedYear: 1949,
        isbn: "9780451524935",
        language: "English",
        publisher: "Secker & Warburg",
        isBookmarked: false,
    },
    {
        title: "The Hobbit",
        author: "J.R.R. Tolkien",
        price: 14.99,
        category: "Fantasy",
        description: "Bilbo Baggins, a hobbit, embarks on an unexpected journey with a group of dwarves to reclaim their mountain home from the dragon Smaug.",
        coverImage: "https://m.media-amazon.com/images/I/710+HcoP38L._AC_UF1000,1000_QL80_.jpg",
        rating: 4.9,
        stock: 20,
        pages: 310,
        publishedYear: 1937,
        isbn: "9780547928227",
        language: "English",
        publisher: "Allen & Unwin",
        isBookmarked: false,
    },
    {
        title: "Harry Potter and the Philosopher's Stone",
        author: "J.K. Rowling",
        price: 15.99,
        category: "Fantasy",
        description: "Harry Potter discovers he's a wizard and begins his education at Hogwarts School of Witchcraft and Wizardry, uncovering secrets about his past.",
        coverImage: "https://m.media-amazon.com/images/I/81m1s4wIPML._AC_UF1000,1000_QL80_.jpg",
        rating: 4.9,
        stock: 25,
        pages: 223,
        publishedYear: 1997,
        isbn: "9780747532699",
        language: "English",
        publisher: "Bloomsbury",
        isBookmarked: false,
    },
    {
        title: "The Catcher in the Rye",
        author: "J.D. Salinger",
        price: 11.99,
        category: "Literary Fiction",
        description: "Holden Caulfield recounts his experiences in New York City after being expelled from prep school, exploring themes of alienation and identity.",
        coverImage: "https://m.media-amazon.com/images/I/71JP7A4KDLL._AC_UF1000,1000_QL80_.jpg",
        rating: 4.0,
        stock: 12,
        pages: 234,
        publishedYear: 1951,
        isbn: "9780316769488",
        language: "English",
        publisher: "Little, Brown and Company",
        isBookmarked: true,
    },
    {
        title: "Pride and Prejudice",
        author: "Jane Austen",
        price: 8.99,
        category: "Classic",
        description: "The romantic clash between the opinionated Elizabeth Bennet and the proud Mr. Darcy in 19th century England.",
        coverImage: "https://m.media-amazon.com/images/I/71Q1tPupKjL._AC_UF1000,1000_QL80_.jpg",
        rating: 4.6,
        stock: 18,
        pages: 279,
        publishedYear: 1813,
        isbn: "9780141439518",
        language: "English",
        publisher: "T. Egerton, Whitehall",
        isBookmarked: false,
    },
    {
        title: "The Lord of the Rings",
        author: "J.R.R. Tolkien",
        price: 24.99,
        category: "Fantasy",
        description: "Frodo Baggins and the Fellowship embark on a quest to destroy the One Ring and defeat the Dark Lord Sauron.",
        coverImage: "https://m.media-amazon.com/images/I/71jLBXtWJWL._AC_UF1000,1000_QL80_.jpg",
        rating: 4.9,
        stock: 15,
        pages: 1178,
        publishedYear: 1954,
        isbn: "9780544003415",
        language: "English",
        publisher: "Allen & Unwin",
        isBookmarked: false,
    },
    {
        title: "The Da Vinci Code",
        author: "Dan Brown",
        price: 13.99,
        category: "Mystery",
        description: "Harvard symbologist Robert Langdon uncovers clues in Leonardo da Vinci's works that lead to a religious mystery protected for centuries.",
        coverImage: "https://m.media-amazon.com/images/I/71YHjVXyR0L._AC_UF1000,1000_QL80_.jpg",
        rating: 4.2,
        stock: 7,
        pages: 489,
        publishedYear: 2003,
        isbn: "9780307474278",
        language: "English",
        publisher: "Doubleday",
        isBookmarked: false,
    },
    {
        title: "Dune",
        author: "Frank Herbert",
        price: 16.99,
        category: "Science Fiction",
        description: "Paul Atreides leads a rebellion on the desert planet Arrakis while grappling with his prescient visions and the planet's valuable spice.",
        coverImage: "https://m.media-amazon.com/images/I/81ym3QUd3KL._AC_UF1000,1000_QL80_.jpg",
        rating: 4.7,
        stock: 9,
        pages: 412,
        publishedYear: 1965,
        isbn: "9780441172719",
        language: "English",
        publisher: "Chilton Books",
        isBookmarked: false,
    },
    {
        title: "My Life in Prison",
        author: "John Kiriamiti",
        price: 12.99,
        category: "Autobiography",
        description: "A gripping autobiographical account of John Kiriamiti's experiences in Kenyan prisons. The book details his transformation from a notorious criminal to a reformed man, offering raw insights into the harsh realities of prison life and the criminal underworld in Kenya during the 1970s and 1980s.",
        coverImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSB6AY4rvEIRIztiIEb5jehkSiargyC3h_8Ag&s",
        rating: 4.7,
        stock: 15,
        pages: 256,
        publishedYear: 1984,
        isbn: "978-9966498529",
        language: "English",
        publisher: "East African Educational Publishers",
        isBookmarked: true,
    }
];